### ISSUE TITLE
No getting any data output

### ISSUE THREAD

**Issue by SuperDuperOne** [janpapenbrock/realtime#4]
Hi @janpapenbrock , 

I understand this is an this hasn't been worked on for quite some time, but I believe is exactly what i'm looking.
 
I've sadly ran into an issue trying to display data. 
this is the terminal output below:

<img width="482" alt="Screen Shot 2019-07-30 at 23 08 58" src="https://user-images.githubusercontent.com/23457220/62169082-0de54c80-b31f-11e9-8e83-325524da14e8.png">

I have connect the Google Account but it's just not pulling in the data -- any idea/help would be greatly appreciated.

thanks! 

```
@macbookpro:/Users/alan/sandbox/dashing_dashboard/realtime git:(master*) $ node index.js -vvv
HTTP: Server started and waiting for connections.
Analytics: Authorization started.
Analytics: Authorization started.
Analytics: Authorized.
Analytics: Authorized.
Socket: A user connected.
HTTP: Request received: /
Router: About to route a request for /
Socket: A user disconnected.
HTTP: Request received: /assets/css/lib/chartist.min.css
Router: About to route a request for /assets/css/lib/chartist.min.css
HTTP: Request received: /assets/css/styles.css
Router: About to route a request for /assets/css/styles.css
HTTP: Request received: /assets/js/lib/jquery-2.1.1.min.js
Router: About to route a request for /assets/js/lib/jquery-2.1.1.min.js
HTTP: Request received: /assets/js/lib/underscore-1.7.0.min.js
Router: About to route a request for /assets/js/lib/underscore-1.7.0.min.js
HTTP: Request received: /assets/js/lib/backbone-1.1.2.min.js
Router: About to route a request for /assets/js/lib/backbone-1.1.2.min.js
HTTP: Request received: /assets/js/lib/chartist.js
Router: About to route a request for /assets/js/lib/chartist.js
HTTP: Request received: /assets/js/lib/colibri.min.js
Router: About to route a request for /assets/js/lib/colibri.min.js
Socket: A user connected.
HTTP: Request received: /favicon.ico
Router: About to route a request for /favicon.ico
```

**Comment by SuperDuperOne** [comment]
as for the google account role it's got VIEWER for all resources and CONTAINER ANALYSIS ADMIN (not sure if that is what you mean when you say "analysis role should suffice"

**Comment by janpapenbrock** [comment]
Hey @SuperDuperOne, wow, I have not looked into this for a few years :) Happy to see you find it useful. Hope I'll have some spare time over the weekend to have a look, but cannot promise anything :)

**Comment by SuperDuperOne** [comment]
Hi @janpapenbrock, 
Thanks for getting back to me and I understand that this project is 5 years old and I appreciate you giving up your time to take a look, however it's exactly what I've been looking for, 
ideally, I would like to have multiple tiles up with reflecting the number of real time visitors our sites currently have. 

Thanks again for looking :)

**Comment by janpapenbrock** [comment]
hey @SuperDuperOne, I just went through the steps in the README again myself and it all worked out - I was suprised, actually :-D

So it works, in general, and now we can work on finding where it goes wrong in your case!

So to clarify, you have to give permissions for the created account.
1) in the [Google Project console](https://console.developers.google.com/iam-admin/iam), the created "Service account" has to have Project  > Viewer role.
2) in Google Analytics > Admin > User management, you need to add the Service account's mail address as an account with "Read & Analyze" permissions

Does that help?

**Comment by SuperDuperOne** [comment]
@janpapenbrock awesome! 
Glad to hear it's still working! I need to figure out what I'm doing wrong :( 
Will it be possible if you could send me over your config/setup to see where the hell I'm going wrong. I've pretty much given the service account full admin access.
let me double check and send you what I have. 

Thanks again! @janpapenbrock

**Comment by SuperDuperOne** [comment]
In google.json file I have: 

> {
>     "email": "projectname@projectname.iam.gserviceaccount.com",
>     "keyPath": "key.pem",
>     "account": {
>         "include": [ "111111111"] (this is the Google Analytics Account Id)
>     },
>     "webProperty": {
>         "exclude": [ "UA-111111-1"] (This is the Properties and Apps Id)
>     },
>     "profile": {
>         "exclude": [ "111111111"] (this is the Views Id)
>     }
> }

the *key.pem*| is within the directory.

**Comment by SuperDuperOne** [comment]
<img width="1676" alt="Screen Shot 2019-08-05 at 22 00 24" src="https://user-images.githubusercontent.com/23457220/62495020-b9354c00-b7cc-11e9-90d2-eabaef9639f7.png">
<img width="696" alt="Screen Shot 2019-08-05 at 22 02 05" src="https://user-images.githubusercontent.com/23457220/62495021-b9354c00-b7cc-11e9-88e3-4ed82463e1c3.png">

**Comment by SuperDuperOne** [comment]
I've just seen this within Google Analytics, 

_"You have access to this account, but you don't have permission to manage this account's users. Without user management permissions, you cannot add/remove users or change other users' permissions.
To manage this account's users, one of this account's administrators must grant you user management permissions.
This account is linked to an organization. You can also contact the organization administrators and ask them to grant you access to this account."_ 


I will ask the other admins to give me access tomorrow and will test again -- I really hope this is the final hurdle.

**Comment by janpapenbrock** [comment]
> In google.json file I have:
> 
> > {
> > "email": "[projectname@projectname.iam.gserviceaccount.com](mailto:projectname@projectname.iam.gserviceaccount.com)",
> > "keyPath": "key.pem",
> > "account": {
> > "include": [ "111111111"] (this is the Google Analytics Account Id)
> > },
> > "webProperty": {
> > "exclude": [ "UA-111111-1"] (This is the Properties and Apps Id)
> > },
> > "profile": {
> > "exclude": [ "111111111"] (this is the Views Id)
> > }
> > }
> 
> the _key.pem_| is within the directory and below shows that there is traffic calls being made with errors too, also the access I've given my service account.

Please note that `webProperty` and `profile` are `exclude` - not `include` - so if you put IDs in there, they will NOT be shown. If you leave those empty, all properties in your account will be shown.

**Comment by janpapenbrock** [comment]
My google.json looks like this:

```{
    "email": "realtimeapp@xyzproject-12345.iam.gserviceaccount.com",
    "keyPath": "key.pem",
    "account": {
        "include": [ "1234567" ]
    },
    "webProperty": {
        "exclude": []
    },
    "profile": {
        "exclude": []
    }
}```

**Comment by SuperDuperOne** [comment]
Hi @janpapenbrock 
I've just now been given Google Admin Access for all the sites now, and will test shortly.

**Comment by janpapenbrock** [comment]
This is what my Analytics permissions look like:

![analytics-account-permissions](https://user-images.githubusercontent.com/2108728/62527560-a86fef00-b83b-11e9-91a3-4ef5b7b94aa1.png)

**Comment by SuperDuperOne** [comment]
Hi @janpapenbrock 
So I've given the service account email address  "Read & Analyze" permissions to the site i want to display, I've also updated the config/google.json file with: 

 "account": {
        "include": [ "1234567" ] this number being the **Analytics Account ID** and not the properties & Apps nor the Views ID
    },

the terminal output is:

HTTP: Server started and waiting for connections.
Analytics: Authorization started.
Analytics: Authorization started.
Analytics: Authorized.
Analytics: Authorized.
HTTP: Request received: /
Router: About to route a request for /
HTTP: Request received: /assets/css/lib/chartist.min.css
Router: About to route a request for /assets/css/lib/chartist.min.css
HTTP: Request received: /assets/css/styles.css
Router: About to route a request for /assets/css/styles.css
HTTP: Request received: /assets/js/lib/jquery-2.1.1.min.js
Router: About to route a request for /assets/js/lib/jquery-2.1.1.min.js
HTTP: Request received: /assets/js/lib/underscore-1.7.0.min.js
Router: About to route a request for /assets/js/lib/underscore-1.7.0.min.js
HTTP: Request received: /assets/js/lib/backbone-1.1.2.min.js
Router: About to route a request for /assets/js/lib/backbone-1.1.2.min.js
HTTP: Request received: /assets/js/lib/chartist.js
Router: About to route a request for /assets/js/lib/chartist.js
HTTP: Request received: /assets/js/lib/colibri.min.js
Router: About to route a request for /assets/js/lib/colibri.min.js
Socket: A user connected.

The current Site at this time that I want displaying has 71 active users on, but my localhost is showing 0

any ideas?

<img width="1440" alt="Screen Shot 2019-08-06 at 11 00 31" src="https://user-images.githubusercontent.com/23457220/62530995-73629d00-b839-11e9-8d9d-2abb961ad164.png">

(Sorry to be a pain)

**Comment by janpapenbrock** [comment]
Does it have "Read & Analyze" on the Account level or the property level? I think it requires permissions on the account level.

**Comment by SuperDuperOne** [comment]
it's got "Read & Analyze" in all 3 levels

<img width="649" alt="Screen Shot 2019-08-06 at 11 11 38" src="https://user-images.githubusercontent.com/23457220/62532041-7b234100-b83b-11e9-8705-5cb15d22808d.png">

**Comment by janpapenbrock** [comment]
Looks correct to me :-/

**Comment by SuperDuperOne** [comment]
Hi @janpapenbrock 
can I send you what I have? without the key.pem so you can see what I have so far...
it's strange since I'm getting traffic through my Google Analytics, but it's not displaying the real time visitors via localhost:8888

![image](https://user-images.githubusercontent.com/23457220/62617982-0c151d80-b90b-11e9-895d-04f723125df5.png)

**Comment by SuperDuperOne** [comment]
[realtime_superDupa.zip](https://github.com/janpapenbrock/realtime/files/3476939/realtime_superDupa.zip)

**Comment by janpapenbrock** [comment]
Can you try empty arrays instead of an array with an empty string in `google.json`?

```
{
...
    "webProperty": {
        "exclude": []
    },
    "profile": {
        "exclude": []
    }
}
```

instead of 

```
{
...
    "webProperty": {
        "exclude": [""]
    },
    "profile": {
        "exclude": [""]
    }
}
```

Shouldn't make any difference, but just to be sure. You don't have any strings in there, right?

**Comment by janpapenbrock** [comment]
Next step could be to start debugging in the code, maybe replace `realtime.js` with this:

```
var analytics = require('./analytics.js');
var faviconLoader = require('./favicon.js');
var googleConfig = require(__dirname + '/../config/google.json');

var io;

function start(ioStream) {
    io = ioStream;
    analytics(requestRealTimeData);
    analytics(requestProfiles);
}

var profiles = [];

var requestProfiles = function(err, analytics) {
    var accountIds = googleConfig.account.include || [];

    console.log("requestProfiles for accountIds", accountIds);

    accountIds.forEach(function(accountId) {
        var params = {
            accountId: accountId,
            webPropertyId: '~all',
            "max-results": 200
        };

        console.log("analytics.management.profiles.list request", accountId);

        analytics.management.profiles.list(params, function(err, data) {
            console.log("analytics.management.profiles.list response", accountId, "- err", err, "data", data);

            if (err) {
                return err;
            }

            data.items.filter(isProfileNotExcluded).forEach(addProfile);
        });
    });
};

var isProfileNotExcluded = function(profile) {
    var excludedWebProperties = googleConfig.webProperty.exclude || [];
    var excludedProfiles      = googleConfig.profile.exclude || [];

    if (excludedWebProperties.indexOf(profile.webPropertyId) > -1) {
        return false;
    }

    if (excludedProfiles.indexOf(profile.id) > -1) {
        return false;
    }

    return true;
};

var addProfile = function(profile) {

    var domain = profile.websiteUrl.split("//")[1].split("/")[0];

    var favicon = '/favicons/' + profile.id + '.png';

    var reducedProfile = {
        id:         profile.id,
        websiteUrl: profile.websiteUrl,
        name:       profile.name,
        domain:     domain,
        favicon:    favicon
    };

    setTimeout(function() {
        faviconLoader.download(reducedProfile);
    }, 0);

    profiles.push(reducedProfile);
};

var requestRealTimeData = function(err, analytics) {
    var loop = require(__dirname + '/../lib/queue-loop.js');

    loop.replace(profiles);

    loop.loop(function(profile) {
        requestRealTimeDataForProfile(analytics, profile)
    }, 250, 1000);
};

var requestRealTimeDataForProfile = function(analytics, profile) {
    var params = {
        ids:     "ga:" + profile.id,
        metrics: 'rt:activeUsers'
    };

    console.log("requesting realtime data for profile", profile);

    analytics.data.realtime.get(params, function(err, data) {
        console.log("requesting realtime data for profile", profile, "response - err", err, "data", data);

        if (err) {
            console.log(err);
            return;
        }

        if (data.totalsForAllResults) {
            profile.activeUsers = data.totalsForAllResults['rt:activeUsers'];
            console.log(profile.name);
            console.log(profile.activeUsers);

            io.emit('data-update', { profile: profile });
        }
    });
};

exports.start = start;
```

**Comment by SuperDuperOne** [comment]
> Can you try empty arrays instead of an array with an empty string in `google.json`?
> 
> ```
> {
> ...
>     "webProperty": {
>         "exclude": []
>     },
>     "profile": {
>         "exclude": []
>     }
> }
> ```
> 
> instead of
> 
> ```
> {
> ...
>     "webProperty": {
>         "exclude": [""]
>     },
>     "profile": {
>         "exclude": [""]
>     }
> }
> ```
> 
> Shouldn't make any difference, but just to be sure. You don't have any strings in there, right?

no joy with this...

**Comment by SuperDuperOne** [comment]
<img width="1680" alt="Screen Shot 2019-08-08 at 13 18 36" src="https://user-images.githubusercontent.com/23457220/62702729-76978d80-b9df-11e9-8b6f-f37d37ed10e7.png">

some progress as i'm getting code 200.... but still no real time visitors....

**Comment by SuperDuperOne** [comment]
Hi @janpapenbrock 
Sorry to bother again, but did you manage to take a look over my last message?
i'm hitting this error message _console.log(
  input.JSON.filter(({ myFavoriteSport }) => myFavoriteSport === 'soccer')
);_ but can't for the life of me find it in realtime.js

any ideas would be greatly appreciated

**Comment by janpapenbrock** [comment]
Hey, sorry. Can you please try the following:

1. fetch the latest version of `master` which I just updated
2. delete `node_modules` directory
3. run `npm ci` in the root of the project to install exactly the same dependency versions I have (as specified in `package-lock.json` now)

I'm running node version `v10.16.0`.

**Comment by janpapenbrock** [comment]
Also you error seems to be caused in this line:

`data.items.filter(isProfileNotExcluded).forEach(addProfile);`

You may want to add `console.log(data)` before that line and see what's in there.

**Comment by SuperDuperOne** [comment]
Hi @janpapenbrock 
thanks for getting back to me, i'll give this a crack now.

**Comment by SuperDuperOne** [comment]
@janpapenbrock  
YOU'RE THE MAN, THANK YOU! 

<img width="789" alt="Screen Shot 2019-08-14 at 09 40 54" src="https://user-images.githubusercontent.com/23457220/63006963-aaf3c980-be77-11e9-8970-86471c421693.png">

thank you for helping me with this!

**Comment by janpapenbrock** [comment]
finally :D :tada:
